# Ative ou desative o uso do bStats (apenas serve para coletar algumas informações sobre o uso do plugin como quantidade de pessoas usando, servidores e etc...)
metrics: true

menu:
  size: 27
  name: "Warps"
  items:
    warp-mina: # Não importa
      icon: DIAMOND_PICKAXE # Ícone do item no menu, suporta tanto IDs como nomes
      slot: 13 # Slot no menu, começa em 1
      name: '&aWarp Mina'
      lore:
        - '&7Warp Mina'
      warp: mina # Warp
    warp-spawn:
      icon: BOOK_AND_QUILL
      slot: 15
      name: '&aSpawn'
      lore:
        - '&7Spawn'
      warp: spawn


config-version: 1
