menu:
  size: 27
  name: "Warps"
  items:
    warp-mina: # Não importa
      icon: DIAMOND_PICKAXE
      data: 0
      slot: 13 # Slot no menu, começa em 1
      name: '&aWarp Mina'
      lore:
        - '&7Warp Mina'
      warp: mina # Warp
    warp-spawn:
      #material: BOOK
      #data: 0
      head: 'Yuhtin'
      slot: 15
      name: '&aSpawn'
      lore:
        - '&7Spawn'
      warp: spawn

config-version: 1
